version: "3"

services:

  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=celery_user
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_VHOST=celery_app
    ports:
      - "15672:15672"

  celery:
    build:
      context: celery_app
      dockerfile: Dockerfile.celery
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  flower:
    build:
      context: celery_app
      dockerfile: Dockerfile.flower
    links:
      - celery
      - rabbitmq
    depends_on:
      - celery
    ports:
      - "5555:5555"
